AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  ## DynamoDB Table
  MySimpleTable:
    Type: 'AWS::Serverless::SimpleTable'
    Properties:
      PrimaryKey:
        Name: id
        Type: Number

  ## Lambda Function
  MyUpdateFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: MyUpdateFunction
      Handler: app.handler
      Runtime: nodejs14.x
      CodeUri: lambdaApp/
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME: !Ref MySimpleTable
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: dynamodb:PutItem
              Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${MySimpleTable}'

  ## API Gateway
  MyApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: Prod
      DefinitionBody:
        swagger: '2.0'
        info:
          title: 'MyAPI'
        paths:
          /update:
            post:
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyUpdateFunction.Arn}/invocations
                passthroughBehavior: 'when_no_match'
                httpMethod: POST
                type: aws_proxy
              responses: {}
              security:
                - sigv4: []

  ## Lambda Function
  MyApiInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt MyUpdateFunction.Arn
      Principal: 'apigateway.amazonaws.com'
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MyApi}/*/*/*'

Outputs:
  ApiURL:
    Description: 'API Gateway endpoint URL'
    Value: !Sub 'https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/update'
