AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  ## DynamoDB Table where users who have accepted the Miro Banner will be captured.
  ## The "id" will be the numeric Miro User ID, stored as string. You may capture a hashed version of the Miro ID in this table (if desired)
  MiroBannerTermsAcceptersTable:
    Type: 'AWS::Serverless::SimpleTable'
    Properties:
      PrimaryKey:
        Name: id
        Type: String

  ## IAM Role for the "Read" Lambda Function to query/read the database
  MiroBannerTermsReadFunctionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: MiroBannerTermsReadFunctionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: MiroBannerTermsDynamoDBReadPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:GetItem'
                Resource: !GetAtt MiroBannerTermsAcceptersTable.Arn
  
  ## IAM Role for the "Write" Lambda Function to write on the database
  MiroBannerTermsWriteFunctionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: MiroBannerTermsWriteFunctionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: MiroBannerTermsDynamoDBWritePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:UpdateItem'
                Resource: !GetAtt MiroBannerTermsAcceptersTable.Arn
  
  ## Lambda "Read" Function
  MiroBannerTermsReadFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: MiroBannerTermsReadFunction
      Handler: app.handler
      Runtime: nodejs14.x
      CodeUri: readApp/
      Timeout: 10
      Role: !GetAtt MiroBannerTermsReadFunctionRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref MiroBannerTermsAcceptersTable

  ## Lambda "Write" Function
  MiroBannerTermsWriteFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: MiroBannerTermsWriteFunction
      Handler: app.handler
      Runtime: nodejs14.x
      CodeUri: writeApp/
      Timeout: 10
      Role: !GetAtt MiroBannerTermsWriteFunctionRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref MiroBannerTermsAcceptersTable

  ## API Gateway
  MiroBannerTermsAPI:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: Prod
      DefinitionBody:
        swagger: '2.0'
        info:
          title: 'MiroBannerTermsAPI'
        paths:
          /w:
            post:
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MiroBannerTermsWriteFunction.Arn}/invocations
                passthroughBehavior: 'when_no_match'
                httpMethod: POST
                type: aws_proxy
              responses: {}
              security:
                - sigv4: []
            options:
              responses:
                '200':
                  description: 'CORS preflight response'
                  headers:
                    Access-Control-Allow-Methods:
                      type: string
                      example: "'POST,OPTIONS'"
                    Access-Control-Allow-Origin:
                      type: string
                      example: "'*'"
          /q:
            get:
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MiroBannerTermsReadFunction.Arn}/invocations
                passthroughBehavior: 'when_no_match'
                httpMethod: POST
                type: aws_proxy
              responses: {}
              security:
                - sigv4: []
      AddDefaultAuthorizerToCorsPreflight: false

  ## "Read" Lambda Function Invoke Permission
  MiroBannerTermsApiInvokePermissionRead:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt MiroBannerTermsReadFunction.Arn
      Principal: 'apigateway.amazonaws.com'
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MiroBannerTermsAPI}/*/*/*'
  
  ## "Write" Lambda Function Invoke Permission
  MiroBannerTermsApiInvokePermissionWrite:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt MiroBannerTermsWriteFunction.Arn
      Principal: 'apigateway.amazonaws.com'
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MiroBannerTermsAPI}/*/*/*'

Outputs:
  WriteApiURL:
    Description: 'API Gateway endpoint URL to write on the MiroBannerTermsAccepters database'
    Value: !Sub 'https://${MiroBannerTermsAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/w'
  ReadApiURL:
    Description: 'API Gateway endpoint URL to read/query the MiroBannerTermsAccepters database'
    Value: !Sub 'https://${MiroBannerTermsAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/q?u=MiroUserId'
